import { describe, expect, it } from 'vitest';
import { PDFDocument, StandardFonts } from 'pdf-lib';
import {
  deletePdfPages,
  imagesToPdf,
  mergePdfs,
  numberPdf,
  reorderPdf,
  rotatePdf,
  splitPdf,
  watermarkPdf,
} from './pdf';
import { pdfDrawnText as drawnText } from './testutils/pdfContent';

/**
 * End-to-end tests for the PDF tools against real documents.
 *
 * These exercise the actual pdf-lib code paths the app runs — no mocks — and
 * assert on the resulting bytes: page counts, rotation angles and recoverable
 * text. Everything here is browser-API-free, so it runs in CI as well.
 *
 * The rasterizing paths (compress, PDF to image) are deliberately absent:
 * they need OffscreenCanvas and are verified in a browser instead.
 */

/** Build a PDF whose pages are individually identifiable. */
async function makePdf(pageCount: number, label = 'Page'): Promise<Blob> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  for (let i = 1; i <= pageCount; i++) {
    const page = doc.addPage([300, 400]);
    page.drawText(`${label} ${i}`, { x: 40, y: 200, size: 24, font });
  }
  return blobOf(await doc.save());
}

/** Wrap generated bytes as a Blob the pipeline accepts. */
function blobOf(bytes: Uint8Array): Blob {
  return new Blob([bytes.slice().buffer as ArrayBuffer], { type: 'application/pdf' });
}

async function pageCountOf(bytes: Uint8Array): Promise<number> {
  const doc = await PDFDocument.load(bytes);
  return doc.getPageCount();
}

async function rotationsOf(bytes: Uint8Array): Promise<number[]> {
  const doc = await PDFDocument.load(bytes);
  return doc.getPages().map((p) => p.getRotation().angle);
}

describe('mergePdfs', () => {
  it('concatenates page counts in order', async () => {
    const merged = await mergePdfs([await makePdf(2), await makePdf(3)]);
    expect(await pageCountOf(merged)).toBe(5);
  });

  it('rejects an empty list', async () => {
    await expect(mergePdfs([])).rejects.toThrow(/nothing to merge/);
  });
});

describe('splitPdf', () => {
  it('produces one single-page document per page', async () => {
    const parts = await splitPdf(await makePdf(3));
    expect(parts).toHaveLength(3);
    for (const part of parts) expect(await pageCountOf(part)).toBe(1);
  });

  it('extracts a range into a single document', async () => {
    const parts = await splitPdf(await makePdf(10), '2-4,8');
    expect(parts).toHaveLength(1);
    expect(await pageCountOf(parts[0]!)).toBe(4);
  });

  it('throws when a range matches no page', async () => {
    await expect(splitPdf(await makePdf(2), '9')).rejects.toThrow(/no pages matched/);
  });
});

describe('rotatePdf', () => {
  it('rotates every page', async () => {
    const rotated = await rotatePdf(await makePdf(2), 90);
    expect(await rotationsOf(rotated)).toEqual([90, 90]);
  });

  it('accumulates on top of existing rotation and wraps at 360', async () => {
    const once = await rotatePdf(await makePdf(1), 270);
    const twice = await rotatePdf(blobOf(once), 180);
    // 270 + 180 = 450 -> 90
    expect(await rotationsOf(twice)).toEqual([90]);
  });
});

describe('reorderPdf', () => {
  it('rebuilds the document in the requested order', async () => {
    const out = await reorderPdf(await makePdf(3), [3, 1, 2]);
    expect(await pageCountOf(out)).toBe(3);
  });

  it('keeps unlisted pages, so no content is lost', async () => {
    const out = await reorderPdf(await makePdf(4), [4]);
    expect(await pageCountOf(out)).toBe(4);
  });
});

describe('deletePdfPages', () => {
  it('removes the listed pages', async () => {
    const out = await deletePdfPages(await makePdf(5), [2, 4]);
    expect(await pageCountOf(out)).toBe(3);
  });

  it('refuses to empty the document', async () => {
    await expect(deletePdfPages(await makePdf(2), [1, 2])).rejects.toThrow(/every page/);
  });

  it('ignores pages that do not exist', async () => {
    const out = await deletePdfPages(await makePdf(2), [99]);
    expect(await pageCountOf(out)).toBe(2);
  });
});

describe('watermarkPdf', () => {
  it('writes the watermark text into every page', async () => {
    const out = await watermarkPdf(await makePdf(2), { text: 'CONFIDENTIAL', opacity: 30 });
    const raw = drawnText(out);
    expect(await pageCountOf(out)).toBe(2);
    // Two pages, each with its own drawn watermark.
    expect(raw.match(/CONFIDENTIAL/g)).toHaveLength(2);
  });

  it('requires text', async () => {
    await expect(watermarkPdf(await makePdf(1), { text: '  ' })).rejects.toThrow(/required/);
  });
});

describe('numberPdf', () => {
  it('numbers pages using the template', async () => {
    const out = await numberPdf(await makePdf(3), { template: 'Page {n} of {total}' });
    const raw = drawnText(out);
    expect(raw).toContain('Page 1 of 3');
    expect(raw).toContain('Page 3 of 3');
  });

  it('honours a custom starting number', async () => {
    // A distinctive prefix so the assertion cannot match a coordinate that
    // happens to contain the same digits.
    const out = await numberPdf(await makePdf(2), { template: 'no.{n}', startAt: 10 });
    const raw = drawnText(out);
    expect(raw).toContain('no.10');
    expect(raw).toContain('no.11');
  });
});

describe('imagesToPdf', () => {
  /** Smallest valid 1x1 PNG. */
  const PNG_1X1 = Uint8Array.from([
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4,
    0x89, 0x00, 0x00, 0x00, 0x0a, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0x00, 0x01, 0x00, 0x00,
    0x05, 0x00, 0x01, 0x0d, 0x0a, 0x2d, 0xb4, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e, 0x44, 0xae,
    0x42, 0x60, 0x82,
  ]);

  it('places one image per page', async () => {
    const image = new Blob([PNG_1X1], { type: 'image/png' });
    const out = await imagesToPdf([image, image], ['a.png', 'b.png'], {});
    expect(await pageCountOf(out)).toBe(2);
  });

  it('fits images onto a standard page size when asked', async () => {
    const image = new Blob([PNG_1X1], { type: 'image/png' });
    const out = await imagesToPdf([image], ['a.png'], { pageSize: 'a4', margin: 20 });
    const doc = await PDFDocument.load(out);
    const page = doc.getPage(0);
    expect(Math.round(page.getWidth())).toBe(595);
    expect(Math.round(page.getHeight())).toBe(842);
  });

  it('rejects an empty list', async () => {
    await expect(imagesToPdf([], [], {})).rejects.toThrow(/no images/);
  });
});
